name: "Deployment"

on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    name: Deploy

    environment:
      name: production
      url: 'https://satisfactory.tii.one'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Install dependencies
        run: composer install --no-interaction --no-progress

      - name: Deploy
        uses: deployphp/action@v1
        with:
          private-key: ${{ secrets.DEPLOY_KEY }}
          dep: deploy --tag ${{ github.ref_name }}
